// 삼괴지역 회원교회 명단 (회원가입 교회명 검색 + 정회원 판별용)
// name: 교회명, pastor: 담임목사, region: 지역
window.CHURCHES = [
  // 우정읍 (31)
  { name: '고온교회', pastor: '심상훈', region: '우정읍' },
  { name: '굳프랜드교회', pastor: '오동길', region: '우정읍' },
  { name: '매향교회', pastor: '정진학', region: '우정읍' },
  { name: '복지교회', pastor: '오대석', region: '우정읍' },
  { name: '새화수교회', pastor: '한길용', region: '우정읍' },
  { name: '생명나무교회', pastor: '박상현', region: '우정읍' },
  { name: '석천교회', pastor: '최현재', region: '우정읍' },
  { name: '성은교회', pastor: '황권선', region: '우정읍' },
  { name: '순복음조암영광교회', pastor: '김정서', region: '우정읍' },
  { name: '신흥비전교회', pastor: '김선미', region: '우정읍' },
  { name: '엘바람교회', pastor: '이정렬', region: '우정읍' },
  { name: '염광교회', pastor: '한준용', region: '우정읍' },
  { name: '영광교회', pastor: '김경진', region: '우정읍' },
  { name: '예손교회', pastor: '김용훈', region: '우정읍' },
  { name: '우정교회(감리)', pastor: '양봉국', region: '우정읍' },
  { name: '우정교회(침례)', pastor: '조인상', region: '우정읍' },
  { name: '운평장로교회', pastor: '김동석', region: '우정읍' },
  { name: '율리교회', pastor: '박현정', region: '우정읍' },
  { name: '이화교회', pastor: '김지웅', region: '우정읍' },
  { name: '인자교회', pastor: '김용구', region: '우정읍' },
  { name: '조암교회', pastor: '조대흥', region: '우정읍' },
  { name: '조암신흥교회', pastor: '장명희', region: '우정읍' },
  { name: '조암중앙교회', pastor: '제재호', region: '우정읍' },
  { name: '주공교회', pastor: '김종호', region: '우정읍' },
  { name: '향원교회', pastor: '우종현', region: '우정읍' },
  { name: '호곡교회', pastor: '박성규', region: '우정읍' },
  { name: '화산교회', pastor: '유승용', region: '우정읍' },
  { name: '화성권능교회', pastor: '류성원', region: '우정읍' },
  { name: '화성소망교회', pastor: '김용태', region: '우정읍' },
  { name: '화수교회', pastor: '남용남', region: '우정읍' },
  { name: '활빈교회', pastor: '권오현', region: '우정읍' },
  // 장안면 (18)
  { name: '길벗교회', pastor: '정한숙', region: '장안면' },
  { name: '꽃밭교회', pastor: '남기훈', region: '장안면' },
  { name: '노진교회', pastor: '손병민', region: '장안면' },
  { name: '노진제일교회', pastor: '박종덕', region: '장안면' },
  { name: '덕성교회', pastor: '이상철', region: '장안면' },
  { name: '독정교회', pastor: '김동천', region: '장안면' },
  { name: '브니엘교회', pastor: '조영애', region: '장안면' },
  { name: '생수교회', pastor: '이영이', region: '장안면' },
  { name: '석포교회', pastor: '박주환', region: '장안면' },
  { name: '시은소교회', pastor: '김낭주', region: '장안면' },
  { name: '예수정안교회', pastor: '이성범', region: '장안면' },
  { name: '장안교회', pastor: '한민규', region: '장안면' },
  { name: '장안제일교회(기감)', pastor: '김요한', region: '장안면' },
  { name: '장안제일교회(통합)', pastor: '김두희', region: '장안면' },
  { name: '조암제일교회', pastor: '김재도', region: '장안면' },
  { name: '주사랑교회', pastor: '이우성', region: '장안면' },
  { name: '축복교회', pastor: '박창대', region: '장안면' },
  { name: '한마음교회', pastor: '김광옥', region: '장안면' }
];
